--- === Symbats ===
---
--- Show a list of Unicode Symbols and Dingbats, copy to pasteboard on select.

local obj = {}
obj.__index = obj

-- luacheck: globals utf8

-- Metadata
obj.name = "Symbats"
obj.version = "1.0"
obj.author = "Spitlo"
obj.license = "MIT - https://opensource.org/licenses/MIT"

obj.choices = {}
obj.chooser = nil
obj.hotkey = nil

local wf = hs.window.filter.defaultCurrentSpace
local pasteboard = require("hs.pasteboard")

function obj.callback(choice)
    local lastFocused = wf:getWindows(wf.sortByFocusedLast)
    if #lastFocused > 0 then
        lastFocused[1]:focus()
    end
    if not choice then
        return
    end
    pasteboard.setContents(hs.utf8.codepointToUTF8(choice.unicode))
end

function obj:init()
    self.choices = {
        -- Miscellaneous Symbols
        {text="☀ Black sun with rays (U+2600)", unicode="U+2600", subText="Clear weather"},
        {text="☁ Cloud (U+2601)", unicode="U+2601", subText="Cloud, cloudy weather"},
        {text="☂ Umbrella (U+2602)", unicode="U+2602", subText="Umbrella, rainy weather"},
        {text="☃ Snowman (U+2603)", unicode="U+2603", subText="Snowman, snowy weather"},
        {text="☄ Comet (U+2604)", unicode="U+2604", subText=""},
        {text="★ Black star (U+2605)", unicode="U+2605", subText=""},
        {text="☆ White star (U+2606)", unicode="U+2606", subText=""},
        {text="☇ Lightning (U+2607)", unicode="U+2607", subText="Lightning"},
        {text="☈ Thunderstorm (U+2608)", unicode="U+2608", subText="Thunderstorm"},
        {text="☉ Sun (U+2609)", unicode="U+2609", subText="Sun, gold"},
        {text="☊ Ascending node (U+260A)", unicode="U+260A", subText=""},
        {text="☋ Descending node (U+260B)", unicode="U+260B", subText=""},
        {text="☌ Conjunction (U+260C)", unicode="U+260C", subText="Open circuit"},
        {text="☍ Opposition (U+260D)", unicode="U+260D", subText="Closed circuit"},
        {text="☎ Black telephone (U+260E)", unicode="U+260E", subText=""},
        {text="☏ White telephone (U+260F)", unicode="U+260F", subText=""},
        {text="☐ Ballot box (U+2610)", unicode="U+2610", subText="Check box, optional information"},
        {text="☑ Ballot box with check (U+2611)", unicode="U+2611", subText=""},
        {text="☒ Ballot box with X (U+2612)", unicode="U+2612", subText=""},
        {text="☓ Saltire (U+2613)", unicode="U+2613", subText=""},
        {text="☔ Umbrella with raindrops (U+2614)", unicode="U+2614", subText="Showery weather"},
        {text="☕ Hot beverage (U+2615)", unicode="U+2615", subText="Tea, coffee, hot chocolate"},
        {text="☖ White shogi piece (U+2616)", unicode="U+2616", subText=""},
        {text="☗ Black shogi piece (U+2617)", unicode="U+2617", subText=""},
        {text="☘ Shamrock (U+2618)", unicode="U+2618", subText="Good luck"},
        {text="☙ Reversed rotated floral heart bullet (U+2619)", unicode="U+2619", subText="Binding signature mark"},
        {text="☚ Black left pointing index (U+261A)", unicode="U+261A", subText=""},
        {text="☛ Black right pointing index (U+261B)", unicode="U+261B", subText=""},
        {text="☜ White left pointing index (U+261C)", unicode="U+261C", subText=""},
        {text="☝ White up pointing index (U+261D)", unicode="U+261D", subText=""},
        {text="☞ White right pointing index (U+261E)", unicode="U+261E", subText=""},
        {text="☟ White down pointing index (U+261F)", unicode="U+261F", subText=""},
        {text="☠ Skull and crossbones (U+2620)", unicode="U+2620", subText="Poison, death"},
        {text="☡ Caution sign (U+2621)", unicode="U+2621", subText=""},
        {text="☢ Radioactive sign (U+2622)", unicode="U+2622", subText="Toxic hazard, nuclear fallout"},
        {text="☣ Biohazard sign (U+2623)", unicode="U+2623", subText="Disease, epidemic, pandemic"},
        {text="☤ Caduceus (U+2624)", unicode="U+2624", subText="Trade"},
        {text="☥ Ankh (U+2625)", unicode="U+2625", subText="Religious symbol"},
        {text="☦ Orthodox cross (U+2626)", unicode="U+2626", subText="Patriarchal cross"},
        {text="☧ Chi Rho (U+2627)", unicode="U+2627", subText="Labarum"},
        {text="☨ Cross of Lorraine (U+2628)", unicode="U+2628", subText="Patriarchal cross"},
        {text="☩ Cross of Jerusalem (U+2629)", unicode="U+2629", subText="Cross potent"},
        {text="☪ Star and crescent (U+262A)", unicode="U+262A", subText="Emblem of Turkey; Islam"},
        {text="☫ Farsi symbol (U+262B)", unicode="U+262B", subText="Coat of arms of Iran"},
        {text="☬ Adi shakti (U+262C)", unicode="U+262C", subText="Khanda"},
        {text="☭ Hammer and sickle (U+262D)", unicode="U+262D", subText="Communism"},
        {text="☮ Peace symbol (U+262E)", unicode="U+262E", subText="Peace"},
        {text="☯ Yin yang (U+262F)", unicode="U+262F", subText="Taoism, balance"},
        {text="☰ Trigram for Heaven (U+2630)", unicode="U+2630", subText=""},
        {text="☱ Trigram for Lake (U+2631)", unicode="U+2631", subText=""},
        {text="☲ Trigram for Fire (U+2632)", unicode="U+2632", subText=""},
        {text="☳ Trigram for Thunder (U+2633)", unicode="U+2633", subText=""},
        {text="☴ Trigram for Wind (U+2634)", unicode="U+2634", subText=""},
        {text="☵ Trigram for Water (U+2635)", unicode="U+2635", subText=""},
        {text="☶ Trigram for Mountain (U+2636)", unicode="U+2636", subText=""},
        {text="☷ Trigram for Earth (U+2637)", unicode="U+2637", subText=""},
        {text="☸ Wheel of Dharma (U+2638)", unicode="U+2638", subText=""},
        {text="☹ White frowning face (U+2639)", unicode="U+2639", subText=""},
        {text="☺ White smiling face (U+263A)", unicode="U+263A", subText=""},
        {text="☻ Black smiling face (U+263B)", unicode="U+263B", subText=""},
        {text="☼ White sun with rays (U+263C)", unicode="U+263C", subText="Compass"},
        {text="☽ First quarter moon (U+263D)", unicode="U+263D", subText="Silver"},
        {text="☾ Last quarter moon (U+263E)", unicode="U+263E", subText=""},
        {text="☿ Mercury (U+263F)", unicode="U+263F", subText="Mercury (planet), mercury (element), Hermaphrodite"},
        {text="♀ Venus (U+2640)", unicode="U+2640", subText="Venus (planet), copper, femininity, Woman"},
        {text="♁ Earth (U+2641)", unicode="U+2641", subText="Antimony"},
        {text="♂ Mars (U+2642)", unicode="U+2642", subText="Mars (planet), iron, masculinity, Man"},
        {text="♃ Jupiter (U+2643)", unicode="U+2643", subText="Jupiter (planet), tin"},
        {text="♄ Saturn (U+2644)", unicode="U+2644", subText="Saturn (planet), lead"},
        {text="♅ Uranus (U+2645)", unicode="U+2645", subText="For the astronomical symbol see U+26E2"},
        {text="♆ Neptune (U+2646)", unicode="U+2646", subText="Neptune (planet)"},
        {text="♇ Pluto (U+2647)", unicode="U+2647", subText="Pluto"},
        {text="♈ Aries (U+2648)", unicode="U+2648", subText="Aries (constellation)"},
        {text="♉ Taurus (U+2649)", unicode="U+2649", subText="Taurus (constellation)"},
        {text="♊ Gemini (U+264A)", unicode="U+264A", subText="Gemini (constellation)"},
        {text="♋ Cancer (U+264B)", unicode="U+264B", subText="Cancer (constellation)"},
        {text="♌ Leo (U+264C)", unicode="U+264C", subText="Leo (constellation)"},
        {text="♍ Virgo (U+264D)", unicode="U+264D", subText="Virgo (constellation)"},
        {text="♎ Libra (U+264E)", unicode="U+264E", subText="Libra (constellation)"},
        {text="♏ Scorpius (U+264F)", unicode="U+264F", subText="Scorpius (constellation), minim"},
        {text="♐ Sagittarius (U+2650)", unicode="U+2650", subText="Sagittarius (constellation)"},
        {text="♑ Capricorn (U+2651)", unicode="U+2651", subText="Capricornus (constellation)"},
        {text="♒ Aquarius (U+2652)", unicode="U+2652", subText="Aquarius (constellation)"},
        {text="♓ Pisces (U+2653)", unicode="U+2653", subText="Pisces (constellation)"},
        {text="♔ White chess king (U+2654)", unicode="U+2654", subText=""},
        {text="♕ White chess queen (U+2655)", unicode="U+2655", subText=""},
        {text="♖ White chess rook (U+2656)", unicode="U+2656", subText=""},
        {text="♗ White chess bishop (U+2657)", unicode="U+2657", subText=""},
        {text="♘ White chess knight (U+2658)", unicode="U+2658", subText=""},
        {text="♙ White chess pawn (U+2659)", unicode="U+2659", subText=""},
        {text="♚ Black chess king (U+265A)", unicode="U+265A", subText=""},
        {text="♛ Black chess queen (U+265B)", unicode="U+265B", subText=""},
        {text="♜ Black chess rook (U+265C)", unicode="U+265C", subText=""},
        {text="♝ Black chess bishop (U+265D)", unicode="U+265D", subText=""},
        {text="♞ Black chess knight (U+265E)", unicode="U+265E", subText=""},
        {text="♟ Black chess pawn (U+265F)", unicode="U+265F", subText=""},
        {text="♠ Black spade suit (U+2660)", unicode="U+2660", subText=""},
        {text="♡ White heart suit (U+2661)", unicode="U+2661", subText=""},
        {text="♢ White diamond suit (U+2662)", unicode="U+2662", subText=""},
        {text="♣ Black club suit (U+2663)", unicode="U+2663", subText=""},
        {text="♤ White spade suit (U+2664)", unicode="U+2664", subText=""},
        {text="♥ Black heart suit (U+2665)", unicode="U+2665", subText=""},
        {text="♦ Black diamond suit (U+2666)", unicode="U+2666", subText=""},
        {text="♧ White club suit (U+2667)", unicode="U+2667", subText=""},
        {text="♨ Hot springs (U+2668)", unicode="U+2668", subText="Onsen"},
        {text="♩ Quarter note (U+2669)", unicode="U+2669", subText="Crotchet"},
        {text="♪ Eighth note (U+266A)", unicode="U+266A", subText="Quaver"},
        {text="♫ Beamed eighth notes (U+266B)", unicode="U+266B", subText="Linked quavers"},
        {text="♬ Beamed sixteenth notes (U+266C)", unicode="U+266C", subText="Linked semi-quavers"},
        {text="♭ Music flat sign (U+266D)", unicode="U+266D", subText=""},
        {text="♮ Music natural sign (U+266E)", unicode="U+266E", subText=""},
        {text="♯ Music sharp sign (U+266F)", unicode="U+266F", subText=""},
        {text="♰ West Syriac cross (U+2670)", unicode="U+2670", subText=""},
        {text="♱ East Syriac cross (U+2671)", unicode="U+2671", subText=""},
        {text="♲ Universal recycling symbol (U+2672)", unicode="U+2672", subText=""},
        -- {text="♳ Recycling symbol for type-1 plastics (U+2673)", unicode="U+2673", subText=""},
        -- {text="♴ Recycling symbol for type-2 plastics (U+2674)", unicode="U+2674", subText=""},
        -- {text="♵ Recycling symbol for type-3 plastics (U+2675)", unicode="U+2675", subText=""},
        -- {text="♶ Recycling symbol for type-4 plastics (U+2676)", unicode="U+2676", subText=""},
        -- {text="♷ Recycling symbol for type-5 plastics (U+2677)", unicode="U+2677", subText=""},
        -- {text="♸ Recycling symbol for type-6 plastics (U+2678)", unicode="U+2678", subText=""},
        -- {text="♹ Recycling symbol for type-7 plastics (U+2679)", unicode="U+2679", subText=""},
        {text="♺ Recycling symbol for generic materials (U+267A)", unicode="U+267A", subText=""},
        -- {text="♻ Black universal recycling symbol (U+267B)", unicode="U+267B", subText=""},
        -- {text="♼ Recycled paper symbol (U+267C)", unicode="U+267C", subText=""},
        -- {text="♽ Partially-recycled paper symbol (U+267D)", unicode="U+267D", subText=""},
        {text="♾ Permanent paper sign (U+267E)", unicode="U+267E", subText=""},
        {text="♿ Wheelchair symbol (U+267F)", unicode="U+267F", subText=""},
        {text="⚀ Die face, 1 (U+2680)", unicode="U+2680", subText=""},
        {text="⚁ Die face, 2 (U+2681)", unicode="U+2681", subText=""},
        {text="⚂ Die face, 3 (U+2682)", unicode="U+2682", subText=""},
        {text="⚃ Die face, 4 (U+2683)", unicode="U+2683", subText=""},
        {text="⚄ Die face, 5 (U+2684)", unicode="U+2684", subText=""},
        {text="⚅ Die face, 6 (U+2685)", unicode="U+2685", subText=""},
        {text="⚆ White circle with dot right (U+2686)", unicode="U+2686", subText=""},
        {text="⚇ White circle with two dots (U+2687)", unicode="U+2687", subText=""},
        {text="⚈ Black circle with white dot right (U+2688)", unicode="U+2688", subText=""},
        {text="⚉ Black circle with two white dots (U+2689)", unicode="U+2689", subText=""},
        {text="⚊ Monogram for yang (U+268A)", unicode="U+268A", subText=""},
        {text="⚋ Monogram for yin (U+268B)", unicode="U+268B", subText=""},
        {text="⚌ Digram for greater yang (U+268C)", unicode="U+268C", subText=""},
        {text="⚍ Digram for lesser yin (U+268D)", unicode="U+268D", subText=""},
        {text="⚎ Digram for lesser yang (U+268E)", unicode="U+268E", subText=""},
        {text="⚏ Digram for greater yin (U+268F)", unicode="U+268F", subText=""},
        {text="⚐ White flag (U+2690)", unicode="U+2690", subText=""},
        {text="⚑ Black flag (U+2691)", unicode="U+2691", subText=""},
        {text="⚒ Hammer and pick (U+2692)", unicode="U+2692", subText="Mining, working day"},
        {text="⚓ Anchor (U+2693)", unicode="U+2693", subText="Nautical term, harbor"},
        {text="⚔ Crossed swords (U+2694)", unicode="U+2694", subText="Military term, battleground, killed in action"},
        {text="⚕ Rod of Asclepius (U+2695)", unicode="U+2695", subText="Medical term"},
        {text="⚖ Scales (U+2696)", unicode="U+2696", subText="Legal term, jurisprudence"},
        {text="⚗ Alembic (U+2697)", unicode="U+2697", subText="Chemical term, chemistry"},
        {text="⚘ Flower (U+2698)", unicode="U+2698", subText="Botanical term"},
        {text="⚙ Gear (U+2699)", unicode="U+2699", subText="Technology, tools"},
        {text="⚚ Staff of Hermes (U+269A)", unicode="U+269A", subText="Caduceus, commercial term, commerce"},
        {text="⚛ Atom symbol (U+269B)", unicode="U+269B", subText="Nuclear installation"},
        {text="⚜ Fleur-de-lis (U+269C)", unicode="U+269C", subText="France, Quebec, Trinity, Scouting"},
        -- {text="⚝ Outlined white star (U+269D)", unicode="U+269D", subText="Coat of arms of Morocco"},
        -- {text="⚞ Three lines converging right (U+269E)", unicode="U+269E", subText="Someone speaking closed captioning symbol (from ARIB STD B24)"},
        -- {text="⚟ Three lines converging left (U+269F)", unicode="U+269F", subText="Background speaking closed captioning symbol (from ARIB STD B24)"},
        {text="⚠ Warning sign (U+26A0)", unicode="U+26A0", subText=""},
        {text="⚡ High voltage sign (U+26A1)", unicode="U+26A1", subText=""},
        {text="⚢ Doubled female sign (U+26A2)", unicode="U+26A2", subText="Female homosexuality"},
        {text="⚣ Doubled male sign (U+26A3)", unicode="U+26A3", subText="Male homosexuality"},
        {text="⚤ Interlocked female and male sign (U+26A4)", unicode="U+26A4", subText="Male or Female bisexuality"},
        {text="⚥ Male and female sign (U+26A5)", unicode="U+26A5", subText="Male or Female heterosexuality, Hermaphrodite (in entomology)"},
        {text="⚦ Male with stroke sign (U+26A6)", unicode="U+26A6", subText="Transgender"},
        {text="⚧ Male with stroke and male and female sign (U+26A7)", unicode="U+26A7", subText="Transgender"},
        {text="⚨ Vertical male with stroke sign (U+26A8)", unicode="U+26A8", subText="Iron (II) sulfate"},
        {text="⚩ Horizontal male with stroke sign (U+26A9)", unicode="U+26A9", subText="Magnesium"},
        {text="⚪ Medium white circle (U+26AA)", unicode="U+26AA", subText="Asexuality, sexless, genderless, engaged, betrothed"},
        {text="⚫ Medium black circle (U+26AB)", unicode="U+26AB", subText="Symbol for record function"},
        {text="⚬ Medium small white circle (U+26AC)", unicode="U+26AC", subText="Engaged, betrothed"},
        {text="⚭ Marriage symbol (U+26AD)", unicode="U+26AD", subText=""},
        {text="⚮ Divorce symbol (U+26AE)", unicode="U+26AE", subText=""},
        {text="⚯ Unmarried partnership symbol (U+26AF)", unicode="U+26AF", subText=""},
        {text="⚰ Coffin (U+26B0)", unicode="U+26B0", subText="Buried (genealogy)"},
        {text="⚱ Funeral urn (U+26B1)", unicode="U+26B1", subText="Cremated (genealogy)"},
        {text="⚲ Neuter (U+26B2)", unicode="U+26B2", subText=""},
        -- {text="⚳ Ceres (U+26B3)", unicode="U+26B3", subText="1 Ceres (dwarf planet)"},
        -- {text="⚴ Pallas (U+26B4)", unicode="U+26B4", subText="2 Pallas"},
        -- {text="⚵ Juno (U+26B5)", unicode="U+26B5", subText="3 Juno"},
        -- {text="⚶ Vesta (U+26B6)", unicode="U+26B6", subText="4 Vesta"},
        -- {text="⚷ Chiron (U+26B7)", unicode="U+26B7", subText="2060 Chiron"},
        -- {text="⚸ Black moon Lilith (U+26B8)", unicode="U+26B8", subText=""},
        -- {text="⚹ Sextile (U+26B9)", unicode="U+26B9", subText="Sal ammoniac"},
        -- {text="⚺ Semisextile (U+26BA)", unicode="U+26BA", subText=""},
        -- {text="⚻ Quincunx (U+26BB)", unicode="U+26BB", subText=""},
        -- {text="⚼ Sesquiquadrate (U+26BC)", unicode="U+26BC", subText=""},
        {text="⚽ Football (U+26BD)", unicode="U+26BD", subText=""},
        {text="⚾ Baseball (U+26BE)", unicode="U+26BE", subText=""},
        -- {text="⚿ Squared key (U+26BF)", unicode="U+26BF", subText="Parental lock (from ARIB STD B24)"},
        -- {text="⛀ White draughts man (U+26C0)", unicode="U+26C0", subText=""},
        -- {text="⛁ White draughts king (U+26C1)", unicode="U+26C1", subText=""},
        -- {text="⛂ Black draughts man (U+26C2)", unicode="U+26C2", subText=""},
        -- {text="⛃ Black draughts king (U+26C3)", unicode="U+26C3", subText=""},
        {text="⛄ Snowman without snow (U+26C4)", unicode="U+26C4", subText="Light snow (from ARIB STD B24)"},
        {text="⛅ Sun behind cloud (U+26C5)", unicode="U+26C5", subText="Partly cloudy (from ARIB STD B24)"},
        -- {text="⛆ Rain (U+26C6)", unicode="U+26C6", subText="Rainy weather (from ARIB STD B24)"},
        -- {text="⛇ Black snowman (U+26C7)", unicode="U+26C7", subText="Heavy snow (from ARIB STD B24)"},
        {text="⛈ Thunder cloud and rain (U+26C8)", unicode="U+26C8", subText="Thunderstorm (from ARIB STD B24)"},
        -- {text="⛉ Turned white shogi piece (U+26C9)", unicode="U+26C9", subText="From ARIB STD B24"},
        -- {text="⛊ Turned black shogi piece (U+26CA)", unicode="U+26CA", subText="From ARIB STD B24"},
        -- {text="⛋ White diamond in square (U+26CB)", unicode="U+26CB", subText="From ARIB STD B24"},
        -- {text="⛌ Crossing lanes (U+26CC)", unicode="U+26CC", subText="Accident (from ARIB STD B24)"},
        -- {text="⛍ Disabled car (U+26CD)", unicode="U+26CD", subText="From ARIB STD B24"},
        -- {text="⛎ Ophiuchus (U+26CE)", unicode="U+26CE", subText="Ophiuchus (astrology), new in Unicode 6."},
        -- {text="⛏ Pick (U+26CF)", unicode="U+26CF", subText="Under construction (from ARIB STD B24)"},
        -- {text="⛐ Car sliding (U+26D0)", unicode="U+26D0", subText="Icy road (from ARIB STD B24)"},
        -- {text="⛑ Helmet with white cross (U+26D1)", unicode="U+26D1", subText="Maintenance (from ARIB STD B24)"},
        -- {text="⛒ Circled crossing lanes (U+26D2)", unicode="U+26D2", subText="Road closed (from ARIB STD B24)"},
        -- {text="⛓ Chains (U+26D3)", unicode="U+26D3", subText="Tyre chains required (from ARIB STD B24)"},
        -- {text="⛔ No entry (U+26D4)", unicode="U+26D4", subText="From ARIB STD B24"},
        -- {text="⛕ Alternate one-way left way traffic (U+26D5)", unicode="U+26D5", subText="From ARIB STD B24"},
        -- {text="⛖ Black two-way left way traffic (U+26D6)", unicode="U+26D6", subText="From ARIB STD B24"},
        -- {text="⛗ White two-way left way traffic (U+26D7)", unicode="U+26D7", subText="From ARIB STD B24"},
        -- {text="⛘ Black left lane merge (U+26D8)", unicode="U+26D8", subText="From ARIB STD B24"},
        -- {text="⛙ White left lane merge (U+26D9)", unicode="U+26D9", subText="From ARIB STD B24"},
        -- {text="⛚ Drive slow sign (U+26DA)", unicode="U+26DA", subText="From ARIB STD B24"},
        -- {text="⛛ Heavy white down-pointing triangle (U+26DB)", unicode="U+26DB", subText="Drive slow (from ARIB STD B24)"},
        -- {text="⛜ Left closed entry (U+26DC)", unicode="U+26DC", subText="From ARIB STD B24"},
        -- {text="⛝ Squared saltire (U+26DD)", unicode="U+26DD", subText="Closed entry (from ARIB STD B24)"},
        -- {text="⛞ Falling diagonal in white circle in black square (U+26DE)", unicode="U+26DE", subText="Closed to large vehicles (from ARIB STD B24)"},
        -- {text="⛟ Black truck (U+26DF)", unicode="U+26DF", subText="Closed to large vehicles, alternate (from ARIB STD B24)"},
        -- {text="⛠ Restricted left entry-1 (U+26E0)", unicode="U+26E0", subText="From ARIB STD B24"},
        -- {text="⛡ Restricted left entry-2 (U+26E1)", unicode="U+26E1", subText="From ARIB STD B24"},
        -- {text="⛢ Astronomical symbol for Uranus (U+26E2)", unicode="U+26E2", subText="New in Unicode 6."},
        -- {text="⛣ Heavy circle with stroke and two dots above (U+26E3)", unicode="U+26E3", subText="Public office (from ARIB STD B24)"},
        -- {text="⛤ Pentagram (U+26E4)", unicode="U+26E4", subText="New in Unicode 6"},
        -- {text="⛥ Right-handed interlaced pentagram (U+26E5)", unicode="U+26E5", subText="New in Unicode 6"},
        -- {text="⛦ Left-handed interlaced pentagram (U+26E6)", unicode="U+26E6", subText="New in Unicode 6"},
        -- {text="⛧ Inverted pentagram (U+26E7)", unicode="U+26E7", subText="New in Unicode 6"},
        -- {text="⛨ Black cross on shield (U+26E8)", unicode="U+26E8", subText="Hospital (from ARIB STD B24)"},
        -- {text="⛩ Shinto shrine (U+26E9)", unicode="U+26E9", subText="Torii (from ARIB STD B24)"},
        -- {text="⛪ Church (U+26EA)", unicode="U+26EA", subText="From ARIB STD B24"},
        -- {text="⛫ Castle (U+26EB)", unicode="U+26EB", subText="From ARIB STD B24"},
        -- {text="⛬ Historic site (U+26EC)", unicode="U+26EC", subText="From ARIB STD B24"},
        -- {text="⛭ Gear without hub (U+26ED)", unicode="U+26ED", subText="Factory (from ARIB STD B24)"},
        -- {text="⛮ Gear with handles (U+26EE)", unicode="U+26EE", subText="Power plant, power substation (from ARIB STD B24)"},
        -- {text="⛯ Map symbol for lighthouse (U+26EF)", unicode="U+26EF", subText="From ARIB STD B24"},
        -- {text="⛰ Mountain (U+26F0)", unicode="U+26F0", subText="From ARIB STD B24"},
        -- {text="⛱ Umbrella on ground (U+26F1)", unicode="U+26F1", subText="Bathing beach (from ARIB STD B24)"},
        -- {text="⛲ Fountain (U+26F2)", unicode="U+26F2", subText="Park (from ARIB STD B24)"},
        -- {text="⛳ Flag in hole (U+26F3)", unicode="U+26F3", subText="Golf course (from ARIB STD B24)"},
        -- {text="⛴ Ferry (U+26F4)", unicode="U+26F4", subText="Ferry boat terminal (from ARIB STD B24)"},
        -- {text="⛵ Sailboat (U+26F5)", unicode="U+26F5", subText="Marina or yacht harbour (from ARIB STD B24)"},
        -- {text="⛶ Square four corners (U+26F6)", unicode="U+26F6", subText="Intersection (from ARIB STD B24)"},
        -- {text="⛷ Skier (U+26F7)", unicode="U+26F7", subText="Ski resort (from ARIB STD B24)"},
        -- {text="⛸ Ice skate (U+26F8)", unicode="U+26F8", subText="Ice skating rink (from ARIB STD B24)"},
        -- {text="⛹ Person with ball (U+26F9)", unicode="U+26F9", subText="Track and field, gymnasium (from ARIB STD B24)"},
        -- {text="⛺ Tent (U+26FA)", unicode="U+26FA", subText="Camping site (from ARIB STD B24)"},
        -- {text="⛻ Japanese bank symbol (U+26FB)", unicode="U+26FB", subText="From ARIB STD B24"},
        -- {text="⛼ Headstone graveyard symbol (U+26FC)", unicode="U+26FC", subText="Graveyard, memorial park, cemetery (from ARIB STD B24)"},
        -- {text="⛽ Fuel pump (U+26FD)", unicode="U+26FD", subText="Petrol station, gas station (from ARIB STD B24)"},
        -- {text="⛾ Cup on black square (U+26FE)", unicode="U+26FE", subText="Drive-in restaurant (from ARIB STD B24)"},
        -- {text="⛿ White flag with horizontal middle black stripe (U+26FF)", unicode="U+26FF", subText="Japanese self-defense force site (from ARIB STD B24)"},
        {text="× Multiplication sign (U+00D7)", unicode="U+00D7", subText="Also known as the times sign or the dimension sign"},

        -- Dingbats
        {text="✀ Black safety scissors (U+2700)", unicode="U+2700", subText=""},
        {text="✁ Upper blade scissors (U+2701)", unicode="U+2701", subText=""},
        {text="✂ Black scissors (U+2702)", unicode="U+2702", subText=""},
        {text="✃ Lower blade scissors (U+2703)", unicode="U+2703", subText=""},
        {text="✄ White scissors (U+2704)", unicode="U+2704", subText=""},
        {text="✅ White heavy check mark (U+2705)", unicode="U+2705", subText=""},
        {text="✆ Telephone location sign (U+2706)", unicode="U+2706", subText=""},
        {text="✇ Tape drive (U+2707)", unicode="U+2707", subText=""},
        {text="✈ Airplane (U+2708)", unicode="U+2708", subText=""},
        {text="✉ Envelope (U+2709)", unicode="U+2709", subText=""},
        {text="✊ Raised fist (U+270A)", unicode="U+270A", subText=""},
        {text="✋ Raised hand (U+270B)", unicode="U+270B", subText=""},
        {text="✌ Victory hand (U+270C)", unicode="U+270C", subText=""},
        {text="✍ Writing hand (U+270D)", unicode="U+270D", subText=""},
        {text="✎ Lower right pencil (U+270E)", unicode="U+270E", subText=""},
        {text="✏ Pencil (U+270F)", unicode="U+270F", subText=""},
        {text="✐ Upper right pencil (U+2710)", unicode="U+2710", subText=""},
        {text="✑ White nib (U+2711)", unicode="U+2711", subText=""},
        {text="✒ Black nib (U+2712)", unicode="U+2712", subText=""},
        {text="✓ Check mark (U+2713)", unicode="U+2713", subText=""},
        {text="✔ Heavy check mark (U+2714)", unicode="U+2714", subText=""},
        {text="✕ Multiplication X (U+2715)", unicode="U+2715", subText=""},
        {text="✖ Heavy multiplication X (U+2716)", unicode="U+2716", subText=""},
        {text="✗ Ballot X (U+2717)", unicode="U+2717", subText=""},
        {text="✘ Heavy ballot X (U+2718)", unicode="U+2718", subText=""},
        {text="✙ Outlined Greek cross (U+2719)", unicode="U+2719", subText=""},
        {text="✚ Heavy Greek cross (U+271A)", unicode="U+271A", subText=""},
        {text="✛ Open center cross (U+271B)", unicode="U+271B", subText=""},
        {text="✜ Heavy open center cross (U+271C)", unicode="U+271C", subText=""},
        {text="✝ Latin cross (U+271D)", unicode="U+271D", subText=""},
        {text="✞ Shadowed white Latin cross (U+271E)", unicode="U+271E", subText=""},
        {text="✟ Outlined Latin cross (U+271F)", unicode="U+271F", subText=""},
        {text="✠ Maltese cross (U+2720)", unicode="U+2720", subText=""},
        {text="✡ Star of David (U+2721)", unicode="U+2721", subText=""},
        {text="✢ Four teardrop-spoked asterisk (U+2722)", unicode="U+2722", subText=""},
        {text="✣ Four balloon-spoked asterisk (U+2723)", unicode="U+2723", subText=""},
        {text="✤ Heavy four balloon-spoked asterisk (U+2724)", unicode="U+2724", subText=""},
        {text="✥ Four club-spoked asterisk (U+2725)", unicode="U+2725", subText=""},
        {text="✦ Black four-pointed star (U+2726)", unicode="U+2726", subText=""},
        {text="✧ White four-pointed star (U+2727)", unicode="U+2727", subText=""},
        {text="✨ Sparkles (U+2728)", unicode="U+2728", subText=""},
        {text="✩ Stress outlined white star (U+2729)", unicode="U+2729", subText=""},
        {text="✪ Circled white star (U+272A)", unicode="U+272A", subText=""},
        {text="✫ Open center black star (U+272B)", unicode="U+272B", subText=""},
        {text="✬ Black center white star (U+272C)", unicode="U+272C", subText=""},
        {text="✭ Outlined black star (U+272D)", unicode="U+272D", subText=""},
        {text="✮ Heavy outlined black star (U+272E)", unicode="U+272E", subText=""},
        {text="✯ Pinwheel star (U+272F)", unicode="U+272F", subText=""},
        {text="✰ Shadowed white star (U+2730)", unicode="U+2730", subText=""},
        {text="✱ Heavy asterisk (U+2731)", unicode="U+2731", subText=""},
        {text="✲ Open center asterisk (U+2732)", unicode="U+2732", subText=""},
        {text="✳ Eight spoked asterisk (U+2733)", unicode="U+2733", subText=""},
        {text="✴ Eight pointed black star (U+2734)", unicode="U+2734", subText=""},
        {text="✵ Eight pointed pinwheel star (U+2735)", unicode="U+2735", subText=""},
        {text="✶ Six pointed black star (U+2736)", unicode="U+2736", subText=""},
        {text="✷ Eight pointed rectilinear black star (U+2737)", unicode="U+2737", subText=""},
        {text="✸ Heavy eight pointed rectilinear black star (U+2738)", unicode="U+2738", subText=""},
        {text="✹ Twelve pointed black star (U+2739)", unicode="U+2739", subText=""},
        {text="✺ Sixteen pointed asterisk (U+273A)", unicode="U+273A", subText=""},
        {text="✻ Teardrop spoked asterisk (U+273B)", unicode="U+273B", subText=""},
        {text="✼ Open center teardrop spoked asterisk (U+273C)", unicode="U+273C", subText=""},
        {text="✽ Heavy teardrop spoked asterisk (U+273D)", unicode="U+273D", subText=""},
        {text="✾ Six petalled black and white florette (U+273E)", unicode="U+273E", subText=""},
        {text="✿ Black florette (U+273F)", unicode="U+273F", subText=""},
        {text="❀ White florette (U+2740)", unicode="U+2740", subText=""},
        {text="❁ Eight petalled outlined black florette (U+2741)", unicode="U+2741", subText=""},
        {text="❂ Circled open center eight pointed star (U+2742)", unicode="U+2742", subText=""},
        {text="❃ Heavy teardrop spoked pinwheel asterisk (U+2743)", unicode="U+2743", subText=""},
        {text="❄ Snowflake (U+2744)", unicode="U+2744", subText=""},
        {text="❅ Tight trifoliate snowflake (U+2745)", unicode="U+2745", subText=""},
        {text="❆ Heavy chevron snowflake (U+2746)", unicode="U+2746", subText=""},
        {text="❇ Sparkle (U+2747)", unicode="U+2747", subText=""},
        {text="❈ Heavy sparkle (U+2748)", unicode="U+2748", subText=""},
        {text="❉ Balloon spoked asterisk (U+2749)", unicode="U+2749", subText=""},
        {text="❊ Eight teardrop spoked propeller asterisk (U+274A)", unicode="U+274A", subText=""},
        {text="❋ Heavy eight teardrop spoked propeller asterisk (U+274B)", unicode="U+274B", subText=""},
        {text="❌ Cross mark (U+274C)", unicode="U+274C", subText=""},
        {text="❍ Shadowed white circle (U+274D)", unicode="U+274D", subText=""},
        {text="❎ Negative squared cross mark (U+274E)", unicode="U+274E", subText=""},
        {text="❏ Lower right drop-shadowed white square (U+274F)", unicode="U+274F", subText=""},
        {text="❐ Upper right drop-shadowed white square (U+2750)", unicode="U+2750", subText=""},
        {text="❑ Lower right shadowed white square (U+2751)", unicode="U+2751", subText=""},
        {text="❒ Upper right shadowed white square (U+2752)", unicode="U+2752", subText=""},
        {text="❓ Black question mark ornament (U+2753)", unicode="U+2753", subText=""},
        {text="❔ White question mark ornament (U+2754)", unicode="U+2754", subText=""},
        {text="❕ White exclamation mark ornament (U+2755)", unicode="U+2755", subText=""},
        {text="❖ Black diamond minus white X (U+2756)", unicode="U+2756", subText=""},
        {text="❗ Heavy exclamation mark symbol (U+2757)", unicode="U+2757", subText=""},
        {text="❘ Light vertical bar (U+2758)", unicode="U+2758", subText=""},
        {text="❙ Medium vertical bar (U+2759)", unicode="U+2759", subText=""},
        {text="❚ Heavy vertical bar (U+275A)", unicode="U+275A", subText=""},
        {text="❛ Heavy single turned comma quotation mark ornament (U+275B)", unicode="U+275B", subText=""},
        {text="❜ Heavy single comma quotation mark ornament (U+275C)", unicode="U+275C", subText=""},
        {text="❝ Heavy double turned comma quotation mark ornament (U+275D)", unicode="U+275D", subText=""},
        {text="❞ Heavy double comma quotation mark ornament (U+275E)", unicode="U+275E", subText=""},
        {text="❜ Heavy low single comma quotation mark ornament (U+275F)", unicode="U+275F", subText=""},
        {text="❞ Heavy low double comma quotation mark ornament (U+2760)", unicode="U+2760", subText=""},
        {text="❡ Curved stem paragraph sign ornament (U+2761)", unicode="U+2761", subText=""},
        {text="❢ Heavy exclamation mark ornament (U+2762)", unicode="U+2762", subText=""},
        {text="❣ Heavy heart exclamation mark ornament (U+2763)", unicode="U+2763", subText=""},
        {text="❤ Heavy black heart (U+2764)", unicode="U+2764", subText=""},
        {text="❥ Rotated heavy black heart bullet (U+2765)", unicode="U+2765", subText=""},
        {text="❦ Floral heart (U+2766)", unicode="U+2766", subText=""},
        {text="❧ Rotated floral heart bullet (U+2767)", unicode="U+2767", subText=""},
        {text="❨ Medium left parenthesis ornament (U+2768)", unicode="U+2768", subText=""},
        {text="❩ Medium right parenthesis ornament (U+2769)", unicode="U+2769", subText=""},
        {text="❪ Medium flattened left parenthesis ornament (U+276A)", unicode="U+276A", subText=""},
        {text="❫ Medium flattened right parenthesis ornament (U+276B)", unicode="U+276B", subText=""},
        {text="❬ Medium left-pointing angle bracket ornament (U+276C)", unicode="U+276C", subText=""},
        {text="❭ Medium right-pointing angle bracket ornament (U+276D)", unicode="U+276D", subText=""},
        {text="❮ Heavy left-pointing angle quotation mark ornament (U+276E)", unicode="U+276E", subText=""},
        {text="❯ Heavy right-pointing angle quotation mark ornament (U+276F)", unicode="U+276F", subText=""},
        {text="❰ Heavy left-pointing angle bracket ornament (U+2770)", unicode="U+2770", subText=""},
        {text="❱ Heavy right-pointing angle bracket ornament (U+2771)", unicode="U+2771", subText=""},
        {text="❲ Light left tortoise shell bracket ornament (U+2772)", unicode="U+2772", subText=""},
        {text="❳ Light right tortoise shell bracket ornament (U+2773)", unicode="U+2773", subText=""},
        {text="❴ Medium left curly bracket ornament (U+2774)", unicode="U+2774", subText=""},
        {text="❵ Medium left curly bracket ornament (U+2775)", unicode="U+2775", subText=""},
        {text="❶ Dingbat negative circled digit one (U+2776)", unicode="U+2776", subText=""},
        {text="❷ Dingbat negative circled digit two (U+2777)", unicode="U+2777", subText=""},
        {text="❸ Dingbat negative circled digit three (U+2778)", unicode="U+2778", subText=""},
        {text="❹ Dingbat negative circled digit four (U+2779)", unicode="U+2779", subText=""},
        {text="❺ Dingbat negative circled digit five (U+277A)", unicode="U+277A", subText=""},
        {text="❻ Dingbat negative circled digit six (U+277B)", unicode="U+277B", subText=""},
        {text="❼ Dingbat negative circled digit seven (U+277C)", unicode="U+277C", subText=""},
        {text="❽ Dingbat negative circled digit eight (U+277D)", unicode="U+277D", subText=""},
        {text="❾ Dingbat negative circled digit nine (U+277E)", unicode="U+277E", subText=""},
        {text="❿ Dingbat negative circled digit ten (U+277F)", unicode="U+277F", subText=""},
        {text="➀ Dingbat circled sans-serif digit one (U+2780)", unicode="U+2780", subText=""},
        {text="➁ Dingbat circled sans-serif digit two (U+2781)", unicode="U+2781", subText=""},
        {text="➂ Dingbat circled sans-serif digit three (U+2782)", unicode="U+2782", subText=""},
        {text="➃ Dingbat circled sans-serif digit four (U+2783)", unicode="U+2783", subText=""},
        {text="➄ Dingbat circled sans-serif digit five (U+2784)", unicode="U+2784", subText=""},
        {text="➅ Dingbat circled sans-serif digit six (U+2785)", unicode="U+2785", subText=""},
        {text="➆ Dingbat circled sans-serif digit seven (U+2786)", unicode="U+2786", subText=""},
        {text="➇ Dingbat circled sans-serif digit eight (U+2787)", unicode="U+2787", subText=""},
        {text="➈ Dingbat circled sans-serif digit nine (U+2788)", unicode="U+2788", subText=""},
        {text="➉ Dingbat circled sans-serif digit ten (U+2789)", unicode="U+2789", subText=""},
        {text="➊ Dingbat negative circled sans-serif digit one (U+278A)", unicode="U+278A", subText=""},
        {text="➋ Dingbat negative circled sans-serif digit two (U+278B)", unicode="U+278B", subText=""},
        {text="➌ Dingbat negative circled sans-serif digit three (U+278C)", unicode="U+278C", subText=""},
        {text="➍ Dingbat negative circled sans-serif digit four (U+278D)", unicode="U+278D", subText=""},
        {text="➎ Dingbat negative circled sans-serif digit five (U+278E)", unicode="U+278E", subText=""},
        {text="➏ Dingbat negative circled sans-serif digit six (U+278F)", unicode="U+278F", subText=""},
        {text="➐ Dingbat negative circled sans-serif digit seven (U+2790)", unicode="U+2790", subText=""},
        {text="➑ Dingbat negative circled sans-serif digit eight (U+2791)", unicode="U+2791", subText=""},
        {text="➒ Dingbat negative circled sans-serif digit nine (U+2792)", unicode="U+2792", subText=""},
        {text="➓ Dingbat negative circled sans-serif digit ten (U+2793)", unicode="U+2793", subText=""},
        {text="➔ Heavy wide-headed rightward arrow (U+2794)", unicode="U+2794", subText=""},
        {text="➕ Heavy plus sign (U+2795)", unicode="U+2795", subText=""},
        {text="➖ Heavy minus sign (U+2796)", unicode="U+2796", subText=""},
        {text="➗ Heavy division sign (U+2797)", unicode="U+2797", subText=""},
        {text="➘ Heavy south east arrow (U+2798)", unicode="U+2798", subText=""},
        {text="➙ Heavy rightward arrow (U+2799)", unicode="U+2799", subText=""},
        {text="➚ Heavy north east arrow (U+279A)", unicode="U+279A", subText=""},
        {text="➛ Drafting point rightward arrow (U+279B)", unicode="U+279B", subText=""},
        {text="➜ Heavy round-tipped rightward arrow (U+279C)", unicode="U+279C", subText=""},
        {text="➝ Triangle-headed rightward arrow (U+279D)", unicode="U+279D", subText=""},
        {text="➞ Heavy triangle-headed rightward arrow (U+279E)", unicode="U+279E", subText=""},
        {text="➟ Dashed triangle-headed rightward arrow (U+279F)", unicode="U+279F", subText=""},
        {text="➠ Heavy dashed triangle-headed rightward arrow (U+27A0)", unicode="U+27A0", subText=""},
        {text="➡ Black rightward arrow (U+27A1)", unicode="U+27A1", subText=""},
        {text="➢ Three-D top-lighted rightward arrowhead (U+27A2)", unicode="U+27A2", subText=""},
        {text="➣ Three-D bottom-lighted rightward arrowhead (U+27A3)", unicode="U+27A3", subText=""},
        {text="➤ Black rightward arrowhead (U+27A4)", unicode="U+27A4", subText=""},
        {text="➥ Heavy black curved downward and rightward arrow (U+27A5)", unicode="U+27A5", subText=""},
        {text="➦ Heavy black curved upward and rightward arrow (U+27A6)", unicode="U+27A6", subText=""},
        {text="➧ Squat black rightward arrow (U+27A7)", unicode="U+27A7", subText=""},
        {text="➨ Heavy concave-pointed black rightward arrow (U+27A8)", unicode="U+27A8", subText=""},
        {text="➩ Right-shaded white rightward arrow (U+27A9)", unicode="U+27A9", subText=""},
        {text="➪ Left-shaded white rightward arrow (U+27AA)", unicode="U+27AA", subText=""},
        {text="➫ Back-tilted shadowed white rightward arrow (U+27AB)", unicode="U+27AB", subText=""},
        {text="➬ Front-tilted shadowed white rightward arrow (U+27AC)", unicode="U+27AC", subText=""},
        {text="➭ Heavy lower right-shadowed white rightward arrow (U+27AD)", unicode="U+27AD", subText=""},
        {text="➮ Heavy upper right-shadowed white rightward arrow (U+27AE)", unicode="U+27AE", subText=""},
        {text="➯ Notched lower right-shadowed white rightward arrow (U+27AF)", unicode="U+27AF", subText=""},
        {text="➰ Curly loop (U+27B0)", unicode="U+27B0", subText=""},
        {text="➱ Notched upper right-shadowed white rightward arrow (U+27B1)", unicode="U+27B1", subText=""},
        {text="➲ Circled heavy white rightward arrow (U+27B2)", unicode="U+27B2", subText=""},
        {text="➳ White-feathered rightward arrow (U+27B3)", unicode="U+27B3", subText=""},
        {text="➴ Black-feathered south east arrow (U+27B4)", unicode="U+27B4", subText=""},
        {text="➵ Black-feathered rightward arrow (U+27B5)", unicode="U+27B5", subText=""},
        {text="➶ Black-feathered north east arrow (U+27B6)", unicode="U+27B6", subText=""},
        {text="➷ Heavy black-feathered south east arrow (U+27B7)", unicode="U+27B7", subText=""},
        {text="➸ Heavy black-feathered rightward arrow (U+27B8)", unicode="U+27B8", subText=""},
        {text="➹ Heavy black-feathered north east arrow (U+27B9)", unicode="U+27B9", subText=""},
        {text="➺ Teardrop-barbed rightward arrow (U+27BA)", unicode="U+27BA", subText=""},
        {text="➻ Heavy teardrop-shanked rightward arrow (U+27BB)", unicode="U+27BB", subText=""},
        {text="➼ Wedge-tailed rightward arrow (U+27BC)", unicode="U+27BC", subText=""},
        {text="➽ Heavy wedge-tailed rightward arrow (U+27BD)", unicode="U+27BD", subText=""},
        {text="➾ Open-outlined rightward arrow (U+27BE)", unicode="U+27BE", subText=""},
        {text="➿ Double curly loop (U+27BF)", unicode="U+27BF", subText=""},
    }

    self.chooser = hs.chooser.new(self.callback)
    self.chooser:rows(8)
    self.chooser:searchSubText(true)
    self.chooser:choices(self.choices)
end

--- Symbats:bindHotkeys(mapping)
--- Method
--- Binds hotkeys for PasswordGenerator
---
--- Parameters:
---  * mapping - A table containing hotkey objifier/key details for the following items:
---   * show - Shows a ist of symbols
function obj:bindHotkeys(mapping)
   local def = {
     show = function()
            if self.chooser:isVisible() then
                self.chooser:hide()
            else
                self.chooser:show()
            end
        end
   }
   hs.spoons.bindHotkeysToSpec(def, mapping)
end

return obj
